import type { StaticImageData } from 'next/image';
import roofLongspanHouse from '@/public/images/roof-longspan-house.jpg';
import roofTileSample from '@/public/images/roof-tile-profile-sample.jpg';
import roofBlueCorrugated from '@/public/images/roof-blue-corrugated.jpg';

export type ProductCategory = 'roofing' | 'solar';

export const categories: Record<
  ProductCategory,
  { title: string; intro: string; service: string }
> = {
  roofing: {
    title: 'Roofing Products',
    intro:
      'Long-span and colored roofing sheets in several profiles. Buy supply only, or have our crew install them.',
    service: 'Roofing',
  },
  solar: {
    title: 'Solar Products',
    intro:
      'Solar panels, hybrid and on-grid inverters, batteries, and the mounting and protection parts that go with them. All prices are VAT inclusive.',
    service: 'Solar power system',
  },
};

/**
 * Product groups, in the order they appear on the Products page.
 * "cards" shows big cards with photos and specs; "list" shows compact rows
 * for small parts.
 */
export const groups = [
  { id: 'roofing-sheets', name: 'Roofing sheets', category: 'roofing', layout: 'cards' },
  { id: 'solar-panels', name: 'Solar panels', category: 'solar', layout: 'cards' },
  { id: 'solax-hybrid', name: 'SolaX hybrid inverters', category: 'solar', layout: 'cards' },
  { id: 'luxpower-inverters', name: 'Luxpower inverters', category: 'solar', layout: 'cards' },
  { id: 'solax-on-grid', name: 'SolaX on-grid inverters', category: 'solar', layout: 'cards' },
  { id: 'batteries', name: 'Batteries', category: 'solar', layout: 'cards' },
  { id: 'monitoring-safety', name: 'Monitoring & rapid shutdown', category: 'solar', layout: 'cards' },
  { id: 'mounting', name: 'Mounting & racking', category: 'solar', layout: 'list' },
  { id: 'breakers', name: 'Breakers & surge protection', category: 'solar', layout: 'list' },
  { id: 'packages', name: 'Complete solar packages', category: 'solar', layout: 'cards' },
] as const satisfies readonly {
  id: string;
  name: string;
  category: ProductCategory;
  layout: 'cards' | 'list';
}[];

export type GroupId = (typeof groups)[number]['id'];

export type Product = {
  /** Unique, URL-safe id. Used for the "Inquire" link to the contact page. */
  id: string;
  category: ProductCategory;
  group: GroupId;
  name: string;
  model?: string;
  description?: string;
  /** Key specs shown on the card. */
  specs: string[];
  /** Full specification list, shown under "Full specifications". */
  details?: string[];
  /** Selling price in pesos. Leave out to show "Ask for price". */
  price?: number;
  priceNote?: string;
  /** An imported image, or a path under /public such as '/images/products/x.png'. */
  image?: StaticImageData | string;
};

const photo = (name: string) => `/images/products/${name}.png`;

const solaxWarranty = 'Warranty: 5 years (10 years if combined with a SolaX battery)';
const mountingSpec = 'Aluminum alloy, Type-A';

export const products: Product[] = [
  // ───────────── Roofing ─────────────
  {
    id: 'longspan-rib-roofing',
    category: 'roofing',
    group: 'roofing-sheets',
    name: 'Long-span rib-type roofing',
    description:
      'Pre-painted long-span sheets cut to the length of your roof, so there are fewer joints and fewer leaks.',
    specs: ['Cut to length', 'Multiple colors', 'Supply only or supply & install'],
    image: roofLongspanHouse,
  },
  {
    id: 'tile-profile-roofing',
    category: 'roofing',
    group: 'roofing-sheets',
    name: 'Tile-profile roofing',
    description:
      'Metal roofing shaped like classic clay tiles. The look of tile, but lighter and faster to install.',
    specs: ['Tile look', 'Multiple colors', 'Supply only or supply & install'],
    image: roofTileSample,
  },
  {
    id: 'corrugated-roofing',
    category: 'roofing',
    group: 'roofing-sheets',
    name: 'Corrugated roofing',
    description:
      'Classic corrugated sheets for homes, warehouses and extensions. Simple, durable and budget-friendly.',
    specs: ['Multiple colors', 'Supply only or supply & install'],
    image: roofBlueCorrugated,
  },

  // ───────────── Solar panels ─────────────
  {
    id: 'trina-vertex-610w',
    category: 'solar',
    group: 'solar-panels',
    name: 'Trina Solar Vertex 610W Bifacial',
    model: 'TSM-NEG19RC.20',
    specs: [
      '610W monocrystalline, bifacial',
      'Up to 22.6% efficiency',
      '2382 × 1134 × 30 mm, 33 kg',
      '12-year product, 30-year performance warranty',
    ],
    details: [
      'Cell type: Monocrystalline',
      'Module dimensions: 2382 × 1134 × 30 mm',
      'Weight: 33 kg',
      'Maximum power (Pmax): 610W',
      'Module efficiency: up to 22.6%',
      'Open-circuit voltage (Voc): ~48.7V',
      'Short-circuit current (Isc): ~14.96A',
      'Maximum power voltage (Vmp): ~40.8V',
      'Maximum power current (Imp): ~14.96A',
      'Operating temperature: −40°C to +85°C',
      'Maximum system voltage: 1500V DC',
      'Product warranty: 12 years',
      'Performance warranty: 30 years',
    ],
    price: 8910,
    image: photo('trina-vertex-610w'),
  },
  {
    id: 'hanersun-topcon-600w',
    category: 'solar',
    group: 'solar-panels',
    name: 'HANERSUN N-TOPCon 600W Bifacial',
    model: 'HN18N-72HT',
    specs: [
      '600W n-type TOPCon, bifacial',
      'Up to 23.2% efficiency',
      '2278 × 1134 × 30 mm, 31.5 kg',
      '15-year product, 30-year power output warranty',
    ],
    details: [
      'Technology: Monocrystalline, n-type TOPCon, bifacial',
      'Dimensions (L × W × H): 2278 × 1134 × 30 mm',
      'Weight: 31.5 kg',
      'Cell count: 144 cells',
      'Efficiency: up to 23.2%',
      'Maximum power output (Pmax): 600W',
      'Maximum system voltage: 1500V',
      'Open-circuit voltage (Voc): ~51.60V',
      'Short-circuit current (Isc): ~15.83A',
      'Temperature coefficient of Pmax: −0.28%/°C',
      'Operating temperature: −40°C to +85°C',
      'Warranty: 15 years product workmanship; 30 years power output with 0.4% annual degradation',
    ],
    price: 9405,
    image: photo('hanersun-topcon-600w'),
  },
  {
    id: 'znshine-600w',
    category: 'solar',
    group: 'solar-panels',
    name: 'ZNShine 600W N-Type Bifacial',
    model: 'UPLDD144 series',
    specs: [
      '600W n-type TOPCon, bifacial double glass',
      '22.2% efficiency',
      '2384 × 1134 × 30 mm, 33.5 kg',
      '12-year product, 30-year output warranty',
    ],
    details: [
      'Technology: Monocrystalline, n-type TOPCon, bifacial double glass',
      'Cell count: 144 half cells (6 × 24)',
      'Dimensions (L × W × H): 2384 × 1134 × 30 mm',
      'Weight: 33.5 kg',
      'Maximum power output (Pmax): 600W',
      'Module efficiency: 22.2%',
      'Maximum power voltage (Vmp): 43.90V',
      'Maximum power current (Imp): 13.67A',
      'Open-circuit voltage (Voc): 52.40V',
      'Short-circuit current (Isc): 14.57A',
      'Temperature coefficient of Pmax: −0.28%/°C',
      'Bifacial factor: 80% ± 10%',
      'Maximum system voltage: 1500V DC',
      'Maximum series fuse: 35A',
      'Operating temperature: −40°C to +85°C',
      'Glass: 2.0 mm + 2.0 mm heat-strengthened, anti-reflective coated',
      'Junction box: IP68, 3 diodes; MC4-compatible connectors',
      'Static load: up to 5400Pa front, 2400Pa rear',
      'Warranty: 12 years product; 30 years power output with 0.4% annual degradation',
    ],
    price: 6500,
    image: photo('znshine-600w'),
  },
  {
    id: 'trina-vertex-n-715w',
    category: 'solar',
    group: 'solar-panels',
    name: 'Trina Solar Vertex N 715W Bifacial',
    model: 'TSM-NEG21C.20',
    specs: [
      '715W n-type TOPCon, bifacial',
      'Up to 23.2% efficiency',
      '2384 × 1303 × 33 mm, 38.7 kg',
      '12-year product, 30-year power output warranty',
    ],
    details: [
      'Technology: Monocrystalline, n-type TOPCon, bifacial',
      'Dimensions (L × W × H): 2384 × 1303 × 33 mm',
      'Weight: 38.7 kg',
      'Cell count: 132 cells',
      'Efficiency: up to 23.2%',
      'Maximum power output (Pmax): 715W',
      'Maximum system voltage: 1500V',
      'Open-circuit voltage (Voc): ~48.6V',
      'Short-circuit current (Isc): ~18.10A',
      'Temperature coefficient of Pmax: −0.30%/°C',
      'Operating temperature: −40°C to +85°C',
      'Warranty: 12 years product workmanship; 30 years power output with 0.4% annual degradation',
    ],
    price: 11682,
    image: photo('trina-vertex-n-715w'),
  },

  // ───────────── SolaX hybrid inverters ─────────────
  {
    id: 'solax-x1-hyb-5',
    category: 'solar',
    group: 'solax-hybrid',
    name: 'SolaX 5kW Single Phase Hybrid Inverter',
    model: 'X1-HYB-5.0-LV',
    specs: [
      '5.0kW output, 230V single-phase',
      '2 MPPTs, 80–520V',
      'Battery 40–60V, up to 120A charging',
      '97.6% maximum efficiency',
    ],
    details: [
      'Type: Hybrid inverter (solar + battery)',
      'Rated output power: 5.0kW',
      'Max DC input voltage: 550V',
      'Nominal DC voltage: 360V',
      'DC voltage range: 80–520V',
      'Output voltage: 230V (single-phase)',
      'Frequency: 50/60Hz',
      'Grid connection: Single-phase grid-tied',
      'Maximum efficiency: 97.6%',
      'European efficiency: 97.0%',
      'Number of MPPTs: 2',
      'MPPT voltage range: 80–520V',
      'Max input current per MPPT: 16A',
      'Battery voltage range: 40–60V',
      'Max battery charging current: 120A',
    ],
    price: 67567.5,
    image: photo('solax-x1-hyb-5'),
  },
  {
    id: 'solax-x1-hyb-6',
    category: 'solar',
    group: 'solax-hybrid',
    name: 'SolaX 6kW Single Phase Hybrid Inverter',
    model: 'X1-HYB-6.0-LV',
    specs: [
      '6.0kW output, 230V single-phase',
      '2 MPPTs, 80–520V',
      'Battery 40–60V, up to 120A charging',
      '5-year warranty (10 with SolaX battery)',
    ],
    details: [
      'Type: Hybrid inverter (solar + battery)',
      'Rated output power: 6.0kW',
      'Max DC input voltage: 550V',
      'Nominal DC voltage: 360V',
      'DC voltage range: 80–520V',
      'Output voltage: 230V (single-phase)',
      'Frequency: 50/60Hz',
      'Grid connection: Single-phase grid-tied',
      'Maximum efficiency: 97.6%',
      'European efficiency: 97.0%',
      'Number of MPPTs: 2',
      'MPPT voltage range: 80–520V',
      'Max input current per MPPT: 16A',
      'Battery voltage range: 40–60V',
      'Max battery charging current: 120A',
      'Dimensions (H × W × D): 460 × 370 × 160 mm',
      'Weight: 37.4 kg',
      solaxWarranty,
    ],
    price: 76230,
    image: photo('solax-x1-hyb-6'),
  },
  {
    id: 'solax-x1-reno-8',
    category: 'solar',
    group: 'solax-hybrid',
    name: 'SolaX 8kW Single Phase Hybrid Inverter (Reno)',
    model: 'X1-Reno-8.0-LV',
    specs: [
      '8.0kW output, 230V single-phase',
      '2 MPPTs, 150–850V',
      '98.2% maximum efficiency',
      '5-year warranty (10 with SolaX battery)',
    ],
    details: [
      'Rated output power: 8.0kW',
      'Max DC input voltage: 1000V',
      'Nominal DC voltage: 360V',
      'DC voltage range: 125–1000V',
      'Output voltage: 230V (single-phase)',
      'Frequency: 50/60Hz',
      'Grid connection: Single-phase grid-tied',
      'Maximum efficiency: 98.2%',
      'European efficiency: 98.0%',
      'Number of MPPTs: 2',
      'MPPT voltage range: 150–850V',
      'Max input current per MPPT: 15A',
      'Dimensions (H × W × D): 460 × 370 × 160 mm',
      'Weight: 13 kg',
      solaxWarranty,
    ],
    price: 100650,
    image: photo('solax-x1-reno-8'),
  },
  {
    id: 'solax-x1-lite-8',
    category: 'solar',
    group: 'solax-hybrid',
    name: 'SolaX 8kW Single Phase Hybrid Inverter (Lite)',
    model: 'X1-Lite-8.0-LV',
    specs: [
      '8.0kW output, 230V single-phase',
      '2 MPPTs, 150–850V',
      '98.2% maximum efficiency',
      '5-year warranty (10 with SolaX battery)',
    ],
    details: [
      'Rated output power: 8.0kW',
      'Max DC input voltage: 1000V',
      'Nominal DC voltage: 360V',
      'DC voltage range: 125–1000V',
      'Output voltage: 230V (single-phase)',
      'Frequency: 50/60Hz',
      'Grid connection: Single-phase grid-tied',
      'Maximum efficiency: 98.2%',
      'European efficiency: 98.0%',
      'Number of MPPTs: 2',
      'MPPT voltage range: 150–850V',
      'Max input current per MPPT: 15A',
      'Dimensions (H × W × D): 460 × 370 × 160 mm',
      'Weight: 13 kg',
      solaxWarranty,
    ],
    price: 112695,
    image: photo('solax-x1-lite-8'),
  },
  {
    id: 'solax-x1-lite-10',
    category: 'solar',
    group: 'solax-hybrid',
    name: 'SolaX 10kW Single Phase Hybrid Inverter',
    model: 'X1-Lite-10.0-LV',
    specs: [
      '10.0kW output, 230V single-phase',
      '2 MPPTs, 50–550V',
      'Battery 40–60V, up to 220A charging',
      '5-year warranty (10 with SolaX battery)',
    ],
    details: [
      'Rated output power: 10.0kW',
      'Max DC input voltage: 600V',
      'Nominal DC voltage: 360V',
      'DC voltage range: 50–550V',
      'Output voltage: 230V (single-phase)',
      'Frequency: 50/60Hz',
      'Grid connection: Single-phase grid-tied',
      'Maximum efficiency: 97.6%',
      'European efficiency: 97.0%',
      'Number of MPPTs: 2',
      'MPPT voltage range: 50–550V',
      'Max input current per MPPT: 16A',
      'Battery voltage range: 40–60V',
      'Max battery charging current: 220A',
      'Dimensions (H × W × D): 652.5 × 462.5 × 259.8 mm',
      'Weight: 37.4 kg',
      solaxWarranty,
    ],
    price: 128535,
    image: photo('solax-x1-lite-10'),
  },
  {
    id: 'solax-x1-lite-12',
    category: 'solar',
    group: 'solax-hybrid',
    name: 'SolaX 12kW Single Phase Hybrid Inverter',
    model: 'X1-Lite-12.0-LV',
    specs: [
      '12.0kW output, 230V single-phase',
      '2 MPPTs, 50–550V',
      'Battery 40–60V, up to 250A charging',
      '5-year warranty (10 with SolaX battery)',
    ],
    details: [
      'Rated output power: 12.0kW',
      'Nominal DC voltage: 360V',
      'Max DC input voltage: 600V',
      'DC voltage range: 50–550V',
      'Output voltage: 230V (single-phase)',
      'Frequency: 50/60Hz',
      'Grid connection: Single-phase grid-connected',
      'Maximum efficiency: 97.6%',
      'European efficiency: 97.0%',
      'Number of MPPTs: 2',
      'MPPT voltage range: 50–550V',
      'Max input current per MPPT: 15A',
      'Battery voltage range: 40–60V',
      'Max battery charging current: 250A',
      'Dimensions (H × W × D): 652.5 × 462.5 × 259.8 mm',
      'Weight: 37.4 kg',
      solaxWarranty,
    ],
    price: 142065,
    image: photo('solax-x1-lite-12'),
  },
  {
    id: 'solax-x3-neo-15k',
    category: 'solar',
    group: 'solax-hybrid',
    name: 'SolaX 15kW Three Phase Hybrid Inverter',
    model: 'X3-NEO-15K-LV',
    specs: [
      '15.0kW output, 400V three-phase',
      '2 MPPTs, 160–950V',
      'Battery 40–60V, up to 300A charging',
      '5-year warranty (10 with SolaX battery)',
    ],
    details: [
      'Rated output power: 15.0kW',
      'Nominal DC voltage: 150V',
      'Max DC input voltage: 1000V',
      'DC voltage range: 150–1000V',
      'Output voltage: 400V (three-phase)',
      'Frequency: 50/60Hz',
      'Grid connection: Three-phase grid-connected',
      'Maximum efficiency: 97.6%',
      'European efficiency: 97.0%',
      'Number of MPPTs: 2',
      'MPPT voltage range: 160–950V',
      'Max input current per MPPT: 36A',
      'Battery voltage range: 40–60V (depending on battery configuration)',
      'Max battery charging current: 300A',
      'Dimensions (H × W × D): 705 × 520 × 258 mm',
      'Weight: 44.6 kg',
      solaxWarranty,
    ],
    price: 226957.5,
    image: photo('solax-x3-neo-15k'),
  },

  // ───────────── Luxpower inverters ─────────────
  ...(['2-year', '5-year'] as const).map(
    (warranty): Product => ({
      id: `luxpower-sna-6k-${warranty}`,
      category: 'solar',
      group: 'luxpower-inverters',
      name: `Luxpower SNA-6K Hybrid Inverter (${warranty} warranty)`,
      model: 'SNA 6K',
      specs: [
        '6,000W continuous output',
        'Up to 8,000W PV input, 2 MPPTs',
        '48V lithium-ion or lead-acid battery',
        'Up to 16 units in parallel',
      ],
      details: [
        'Rated output power (AC): ~6,000W continuous',
        'PV input (DC): up to ~8,000W total, 2 MPPT trackers (~4,000W each)',
        'PV input voltage range: ~100–480V DC',
        'MPPT voltage range: ~120–385V DC',
        'Max PV input current per MPPT: ~17A',
        'Battery: lithium-ion or lead-acid; nominal ~48V; range ~38.4–60V DC',
        'Max charge / discharge current: ~125A / 140A',
        'AC output: 120/240V split-phase, 50/60Hz',
        'Parallel capability: up to 16 units (up to ~96kW)',
        'Protections: over/under voltage, over-current, short-circuit; generator input port',
        'Remote monitoring: WiFi / RS485 / CAN; LCD/LED interface',
        'Efficiency: max ~93%; MPPT up to ~99.9%',
        'Indoor rating IP20; operating temperature ~−15°C to +60°C',
        'Weight ~14.5 kg; size ~330 × 505 × 135 mm',
        `Warranty: ${warranty === '2-year' ? '2 years' : '5 years'}`,
      ],
      price: warranty === '2-year' ? 42900 : 57172.5,
      image: photo('luxpower-sna-6k'),
    }),
  ),
  ...(['2-year', '5-year'] as const).map(
    (warranty): Product => ({
      id: `luxpower-sna-14k-${warranty}`,
      category: 'solar',
      group: 'luxpower-inverters',
      name: `Luxpower SNA-14K Hybrid Inverter (${warranty} warranty)`,
      model: 'SNA 14K',
      specs: [
        '12kW continuous output',
        'Up to ~24kW PV input, 2 MPPTs',
        '48V lithium-ion or lead-acid battery',
        'Up to 16 units in parallel',
      ],
      details: [
        'Rated output power (AC): 12kW continuous',
        'Max DC PV input: ~24kW (2 MPPTs with 4 strings)',
        'DC input voltage range: 100–480V DC',
        'MPPT voltage range: ~120–385V DC',
        'Start-up voltage: ~100V DC',
        'Max DC input current per MPPT: ~35A',
        'Battery: lithium-ion and lead-acid; nominal ~48V',
        'Max charge / discharge current: ~250A',
        'Generator / AC coupling input: up to ~19.2kW on some models',
        'Parallel capability: up to 16 units',
        'Size: ~530 × 830 × 150 mm; weight ~40–45 kg',
        'Operating temperature: approx. −25°C to +60°C',
        'Protection rating: IP20 (indoor)',
        'Efficiency: MPPT ~99%; overall ~93% or more',
        'Switching time (UPS / backup): ~10 ms',
        `Warranty: ${warranty === '2-year' ? '2 years' : '5 years'}`,
      ],
      price: warranty === '2-year' ? 123750 : 150727.5,
      image: photo('luxpower-sna-14k'),
    }),
  ),
  {
    id: 'luxpower-geta-1-5k',
    category: 'solar',
    group: 'luxpower-inverters',
    name: 'Luxpower GETA 1.5K/12V Inverter',
    model: 'GETA 1.5K/12V',
    specs: [
      '2kW continuous output',
      'Up to ~2,000W PV input, 1 MPPT',
      '12V battery',
      '2-year warranty',
    ],
    details: [
      'Rated output power (AC): 2kW continuous',
      'Max DC PV input: ~2,000W (1 MPPT with 1 string)',
      'DC input voltage range: 100–500V DC',
      'MPPT voltage range: ~50–450V DC',
      'Start-up voltage: ~45V DC',
      'Max DC input current per MPPT: ~18A',
      'Battery: nominal ~12V',
      'Max charge / discharge current: ~230A',
      'Parallel capability: No',
      'Size: ~307 × 418 × 111 mm; weight ~6 kg',
      'Operating temperature: approx. −10°C to +55°C',
      'Protection rating: IP21 (indoor)',
      'Efficiency: MPPT ~99%; overall ~93% or more',
      'Switching time (UPS / backup): ~10 ms',
      'Warranty: 2 years',
    ],
    price: 18232.5,
    image: photo('luxpower-geta-1-5k'),
  },
  {
    id: 'luxpower-geta-3-6k',
    category: 'solar',
    group: 'luxpower-inverters',
    name: 'Luxpower GETA 3.6K/24V Inverter',
    model: 'GETA 3.6K/24V',
    specs: [
      '4kW continuous output',
      'Up to ~4,000W PV input, 1 MPPT',
      '24V battery',
      '2-year warranty',
    ],
    details: [
      'Rated output power (AC): 4kW continuous',
      'Max DC PV input: ~4,000W (1 MPPT with 1 string)',
      'DC input voltage range: 50–500V DC',
      'MPPT voltage range: ~50–450V DC',
      'Start-up voltage: ~50V DC',
      'Max DC input current per MPPT: ~18A',
      'Battery: nominal ~24V',
      'Max charge / discharge current: ~230A',
      'Parallel capability: No',
      'Size: ~307.4 × 418 × 111 mm; weight ~7 kg',
      'Operating temperature: approx. −10°C to +55°C',
      'Protection rating: IP21 (indoor)',
      'Efficiency: MPPT ~99%; overall ~93% or more',
      'Switching time (UPS / backup): ~10 ms',
      'Warranty: 2 years',
    ],
    price: 26853.75,
    image: photo('luxpower-geta-3-6k'),
  },
  {
    id: 'luxpower-sna-eu-6-5k',
    category: 'solar',
    group: 'luxpower-inverters',
    name: 'LuxPower SNA3 Series 6.5kW Hybrid Inverter',
    model: 'SNA-EU-6.5K',
    specs: ['Wide PV range', 'EU version (230Vac / 220Vac)', 'IP65', '5-year warranty'],
    price: 52800,
    image: photo('luxpower-sna-eu-6-5k'),
  },
  {
    id: 'luxpower-gen2-6k',
    category: 'solar',
    group: 'luxpower-inverters',
    name: 'LuxPower 6kW Hybrid Inverter (GEN2)',
    model: 'GEN2-LB-EU-6K (Single Phase)',
    specs: ['120A charge / discharge current', 'IP65', 'EU version (230Vac / 220Vac)'],
    price: 72600,
    image: photo('luxpower-gen2-6k'),
  },
  {
    id: 'luxpower-sna-12000-wpv',
    category: 'solar',
    group: 'luxpower-inverters',
    name: 'LuxPower ECO 12kW Hybrid Inverter',
    model: 'SNA 12000 WPV',
    specs: ['Wide PV range', 'EU version (230Vac / 220Vac), with breaker', '5-year warranty'],
    price: 118800,
    image: photo('luxpower-sna-12000-wpv'),
  },
  {
    id: 'luxpower-gen2-12k',
    category: 'solar',
    group: 'luxpower-inverters',
    name: 'LuxPower 2nd Generation 12kW Hybrid Inverter',
    model: 'GEN2-LB-EU-12K (Single Phase)',
    specs: ['Parallel function included', '48V battery'],
    price: 131670,
    image: photo('luxpower-gen2-12k'),
  },
  {
    id: 'luxpower-trip2-lb-20k',
    category: 'solar',
    group: 'luxpower-inverters',
    name: 'LuxPower 20kW Three Phase Hybrid Inverter',
    model: 'TriP2-LB-3P 20K (Three Phase, 400V)',
    specs: ['20kW AC output', '230Vac / 400Vac', 'Battery voltage 40–60V', '5-year warranty'],
    price: 206250,
    image: photo('luxpower-trip2-lb-20k'),
  },
  {
    id: 'luxpower-trip2-hb-30k',
    category: 'solar',
    group: 'luxpower-inverters',
    name: 'LuxPower 30kW Three Phase Hybrid Inverter',
    model: 'TriP2-HB-3P 30K (Three Phase, 400V)',
    specs: ['30kW AC output', '230Vac / 400Vac', 'Battery voltage 100–700V', '5-year warranty'],
    price: 270600,
    image: photo('luxpower-trip2-hb-30k'),
  },

  // ───────────── SolaX on-grid inverters ─────────────
  {
    id: 'solax-x1-mini-3k',
    category: 'solar',
    group: 'solax-on-grid',
    name: 'SolaX 3.0kW Single Phase On-grid String Inverter',
    model: 'X1-MINI-3.0K-G4',
    specs: ['3,000W rated AC output', '1 MPPT, 40–450V', '98% max efficiency, IP66', '10-year warranty'],
    details: [
      'Max PV array input power: 6,000W',
      'Max PV input voltage: 450V',
      'Start-up voltage: 50V',
      'MPPT voltage range: 40–450V',
      'MPP trackers / strings per tracker: 1 / 1',
      'Max PV input current: 16A',
      'Rated AC output power: 3,000W',
      'Max AC output apparent power: 3,300VA',
      'Nominal AC voltage / range: 220/230/240V; 90–285V',
      'Nominal AC frequency / range: 50/60Hz; ±5Hz',
      'Rated AC output current: 13.1A',
      'Power factor range: 0.8 leading to 0.8 lagging',
      'Total harmonic distortion (THD): <3%',
      'Maximum efficiency: 98%',
      'European efficiency: 96%',
      'Ingress protection: IP66',
      'Operating temperature: −25°C to 60°C',
      'Max operating altitude: 4,000 m',
      'Relative humidity: 0–100%',
      'Cooling: Natural convection',
      'Dimensions (W × H × D): 290 × 206 × 120 mm',
      'Weight: 5.5 kg',
      'Warranty: 10 years',
    ],
    price: 36300,
    image: photo('solax-x1-mini-3k'),
  },
  {
    id: 'solax-x1-boost-5k',
    category: 'solar',
    group: 'solax-on-grid',
    name: 'SolaX 5.0kW Single Phase On-grid String Inverter',
    model: 'X1-BOOST-5K-G4',
    specs: ['5,000W rated AC output', '2 MPPTs, 40–560V', '98% max efficiency, IP66', '10-year warranty'],
    details: [
      'Max PV input power: 10,000W',
      'Max PV input voltage: 600V',
      'Nominal PV input voltage: 360V',
      'Operating voltage range: 35–600V',
      'MPPT voltage range: 40–560V',
      'Start-up voltage: 50V',
      'MPP trackers / strings per tracker: 2 / 1',
      'Max input current per MPPT: 16A',
      'Rated AC output power: 5,000W',
      'Max AC output apparent power: 5,500VA',
      'Nominal AC voltage / range: 220/230/240V; 180–280V',
      'Nominal AC frequency / range: 50/60Hz; ±5Hz',
      'Rated AC output current: 21.7A',
      'Maximum efficiency: 98%',
      'European efficiency: 97%',
      'Ingress protection: IP66',
      'Operating temperature: −25°C to 60°C',
      'Max operating altitude: 4,000 m',
      'Relative humidity: 0–100%',
      'Cooling: Natural convection',
      'Dimensions (W × H × D): 404 × 274 × 146 mm',
      'Weight: 11 kg',
      'Warranty: 10 years',
    ],
    price: 46200,
    image: photo('solax-x1-boost-5k'),
  },
  {
    id: 'solax-x1-boost-6k',
    category: 'solar',
    group: 'solax-on-grid',
    name: 'SolaX 6.0kW Single Phase On-grid String Inverter',
    model: 'X1-BOOST-6K-G4',
    specs: ['6,000W rated AC output', '2 MPPTs, 40–560V', '98% max efficiency, IP66', '10-year warranty'],
    details: [
      'Max PV input power: 12,000W',
      'Max PV input voltage: 600V',
      'Nominal PV input voltage: 360V',
      'Operating voltage range: 35–600V',
      'MPPT voltage range: 40–560V',
      'Start-up voltage: 50V',
      'MPP trackers / strings per tracker: 2 / 1',
      'Max input current per MPPT: 16A',
      'Rated AC output power: 6,000W',
      'Max AC output apparent power: 6,600VA',
      'Nominal AC voltage / range: 220/230/240V; 180–280V',
      'Nominal AC frequency / range: 50/60Hz; ±5Hz',
      'Rated AC output current: 26.1A',
      'Power factor range: 0.8 leading to 0.8 lagging',
      'Total harmonic distortion (THD): <3%',
      'Maximum efficiency: 98%',
      'European efficiency: 97%',
      'Ingress protection: IP66',
      'Dimensions (W × H × D): 404 × 274 × 146 mm',
      'Weight: 11 kg',
      'Warranty: 10 years',
    ],
    price: 49500,
    image: photo('solax-x1-boost-6k'),
  },
  {
    id: 'solax-x1-smt-8k',
    category: 'solar',
    group: 'solax-on-grid',
    name: 'SolaX 8.0kW Single Phase On-grid String Inverter',
    model: 'X1-SMT-8K-G2',
    specs: ['8,000W rated AC output', '3 MPPTs, 40–560V', '98.2% max efficiency, IP66', '10-year warranty'],
    details: [
      'Max PV input power: 12,000W',
      'Max PV input voltage: 600V',
      'Nominal PV input voltage: 360V',
      'Operating voltage range: 35–600V',
      'MPPT voltage range: 40–560V',
      'Start-up voltage: 50V',
      'MPP trackers / strings per tracker: 3 / 1',
      'Max input current per MPPT: 20A',
      'Rated AC output power: 8,000W',
      'Max AC output apparent power: 8,800VA',
      'Nominal AC voltage / range: 220/230/240V; 180–280V',
      'Nominal AC frequency / range: 50/60Hz; ±5Hz',
      'Rated AC output current: 34.8A',
      'Maximum efficiency: 98.2%',
      'European efficiency: 97.5%',
      'Ingress protection: IP66',
      'Operating temperature: −25°C to 60°C',
      'Max operating altitude: 4,000 m',
      'Relative humidity: 0–100%',
      'Cooling: Natural convection',
      'Dimensions (W × H × D): 515 × 370 × 170 mm',
      'Weight: 19.5 kg',
      'Warranty: 10 years',
    ],
    price: 69300,
    image: photo('solax-x1-smt-8k'),
  },
  {
    id: 'solax-x1-smt-10k',
    category: 'solar',
    group: 'solax-on-grid',
    name: 'SolaX 10.0kW Single Phase On-grid String Inverter',
    model: 'X1-SMT-10K-G2',
    specs: ['10,000W rated AC output', '3 MPPTs, 40–560V', '98.2% max efficiency, IP66', '10-year warranty'],
    details: [
      'Max PV input power: 20,000W',
      'Max PV input voltage: 600V',
      'Nominal PV input voltage: 360V',
      'Operating voltage range: 35–600V',
      'MPPT voltage range: 40–560V',
      'Start-up voltage: 50V',
      'MPP trackers / strings per tracker: 3 / 1',
      'Max input current per MPPT: 20A',
      'Rated AC output power: 10,000W',
      'Max AC output apparent power: 10,000VA',
      'Nominal AC voltage / range: 220/230/240V; 180–280V',
      'Nominal AC frequency / range: 50/60Hz; ±5Hz',
      'Rated AC output current: 43.5A',
      'Power factor range: 0.8 leading to 0.8 lagging',
      'Total harmonic distortion (THD): <3%',
      'Maximum efficiency: 98.2%',
      'European efficiency: 97.5%',
      'Ingress protection: IP66',
      'Dimensions (W × H × D): 515 × 370 × 170 mm',
      'Weight: 19.5 kg',
      'Warranty: 10 years',
    ],
    price: 81427.5,
    image: photo('solax-x1-smt-10k'),
  },
  {
    id: 'solax-x3-mga-20k',
    category: 'solar',
    group: 'solax-on-grid',
    name: 'SolaX 20.0kW Three Phase On-grid String Inverter',
    model: 'X3-MGA-20K-G2-LV',
    specs: ['20kW nominal AC output', '2 MPPTs, 180–650V', 'Up to 30kWp PV array', '5-year warranty'],
    details: [
      'Max PV array input power: 30kWp',
      'Max PV input voltage: 800V',
      'Nominal input voltage: 360V',
      'Start-up voltage: 200V',
      'MPPT voltage range: 180–650V',
      'Number of MPPTs: 2',
      'Max input current per MPPT: 32A',
      'Max short-circuit current per MPPT: 46A',
      'Nominal AC output power: 20kW',
      'Nominal AC output current: 52.5A',
      'Max AC output apparent power: 22kVA',
      'Max AC output current: 57.8A',
      'Dimensions (W × H × D): 630 × 521 × 286 mm',
      'Weight: 44 kg',
      'Display / communication: RS485, PLC (optional), Pocket WiFi, LAN, 4G (optional), USB',
      'Warranty: 5 years',
    ],
    price: 204600,
    image: photo('solax-x3-mga-20k'),
  },
  {
    id: 'solax-x3-fth-50k',
    category: 'solar',
    group: 'solax-on-grid',
    name: 'SolaX 50.0kW Three Phase On-grid String Inverter',
    model: 'X3-FTH-50K-LV',
    specs: ['50kW nominal AC output', '6 MPPTs, 180–650V', 'Up to 75kWp PV array', '5-year warranty'],
    details: [
      'Max PV array input power: 75kWp',
      'Max PV input voltage: 800V',
      'Nominal input voltage: 360V',
      'Start-up voltage: 200V',
      'MPPT voltage range: 180–650V',
      'Number of MPPTs: 6',
      'Strings per MPPT: 2',
      'Max input current per MPPT: 32A',
      'Max short-circuit current per MPPT: 46A',
      'Nominal AC output power: 50kW',
      'Nominal AC output current: 131.3A',
      'Max AC output apparent power: 55kVA',
      'Max AC output current: 144.5A',
      'Dimensions (W × H × D): 985 × 660 × 327.5 mm',
      'Weight: 80.5 kg',
      'Display / communication: RS485, PLC (optional), Pocket WiFi, LAN, 4G (optional), USB',
      'Warranty: 5 years',
    ],
    price: 363825,
    image: photo('solax-x3-fth-50k'),
  },
  {
    id: 'solax-x3-fth-70k',
    category: 'solar',
    group: 'solax-on-grid',
    name: 'SolaX 70.0kW Three Phase On-grid String Inverter',
    model: 'X3-FTH-70K-LV',
    specs: ['70kW nominal AC output', '9 MPPTs, 180–650V', 'Up to 105kWp PV array', '5-year warranty'],
    details: [
      'Max PV array input power: 105kWp',
      'Max PV input voltage: 800V',
      'Nominal input voltage: 360V',
      'Start-up voltage: 200V',
      'MPPT voltage range: 180–650V',
      'Number of MPPTs: 9',
      'Strings per MPPT: 2',
      'Max input current per MPPT: 32A',
      'Max short-circuit current per MPPT: 46A',
      'Nominal AC output power: 70kW',
      'Nominal AC output current: 183.7A',
      'Max AC output apparent power: 70kVA',
      'Max AC output current: 183.7A',
      'Dimensions (W × H × D): 985 × 660 × 327.5 mm',
      'Weight: 83 kg',
      'Display / communication: RS485, PLC (optional), Pocket WiFi, LAN, 4G (optional), USB',
      'Warranty: 5 years',
    ],
    price: 405405,
    image: photo('solax-x3-fth-70k'),
  },

  // ───────────── Batteries ─────────────
  {
    id: 'solax-ld51',
    category: 'solar',
    group: 'batteries',
    name: 'SolaX LD51 5.12kWh 100Ah LFP Battery',
    model: 'TSYS-LD51',
    specs: [
      '5.12kWh, 51.2V lithium iron phosphate',
      '4.6kWh usable (90% DOD)',
      'Over 6,000 cycles',
      '5-year warranty (10 with SolaX inverter)',
    ],
    details: [
      'Cell type: Lithium iron phosphate (LFP)',
      'Nominal voltage: 51.2V',
      'Nominal capacity: 5.12kWh',
      'Usable energy (90% DOD): 4.6kWh',
      'Dimensions (W × H × D): 600 × 168 × 376 mm',
      'Weight: 45 kg',
      'Nominal operation current: 60A',
      'Maximum operation current: 70A',
      'Depth of discharge (DOD): 90%',
      'Cycle life: over 6,000 cycles',
      'Operating temperature: −30°C to 53°C',
      'Ingress protection: IP66',
      'Communication: CAN + RS485',
      'Warranty: 5 years (10 years with SolaX inverter + battery)',
    ],
    price: 74250,
    image: photo('solax-ld51'),
  },
  {
    id: 'solax-ld117',
    category: 'solar',
    group: 'batteries',
    name: 'SolaX LD117 11.77kWh 230Ah LFP Battery',
    model: 'TSYS-LD117',
    specs: [
      '11.77kWh, 51.2V lithium iron phosphate',
      '10.59kWh usable (90% DOD)',
      'Over 6,000 cycles',
      '5-year warranty (10 with SolaX inverter)',
    ],
    details: [
      'Cell type: Lithium iron phosphate (LFP)',
      'Nominal voltage: 51.2V',
      'Nominal capacity: 11.77kWh',
      'Usable energy (90% DOD): 10.59kWh',
      'Dimensions (W × H × D): 263 × 359 × 723 mm',
      'Weight: 86 kg',
      'Nominal operation current: 115A',
      'Maximum operation current: 250A',
      'Depth of discharge (DOD): 90%',
      'Cycle life: over 6,000 cycles',
      'Operating temperature: −20°C to 55°C',
      'Ingress protection: IP40',
      'Communication: CAN + RS485',
      'Warranty: 5 years (10 years with SolaX inverter + battery)',
    ],
    price: 162030,
    image: photo('solax-ld117'),
  },
  {
    id: 'solax-ld160',
    category: 'solar',
    group: 'batteries',
    name: 'SolaX LD160 15.2kWh 314Ah LFP Battery',
    model: 'TSYS-LD160',
    specs: [
      '15.2kWh, 51.2V lithium iron phosphate',
      '90% depth of discharge',
      'Over 6,000 cycles',
      '5-year warranty (10 with SolaX inverter)',
    ],
    details: [
      'Cell type: Lithium iron phosphate (LFP)',
      'Nominal voltage: 51.2V',
      'Nominal capacity: 15.2kWh',
      'Weight: 115.5 kg',
      'Depth of discharge (DOD): 90%',
      'Cycle life: over 6,000 cycles',
      'Operating temperature: −30°C to 53°C',
      'Ingress protection: IP66',
      'Communication: CAN + RS485',
      'Warranty: 5 years (10 years with SolaX inverter + battery)',
    ],
    price: 171600,
    image: photo('solax-ld160'),
  },
  {
    id: 'luxpower-li-7-5e',
    category: 'solar',
    group: 'batteries',
    name: 'Luxpower Li-7.5e Stackable Lithium Battery',
    model: 'Li-7.5e (Low Voltage, IP20)',
    specs: [
      '7.5kWh, 25.6V, 300Ah',
      'Max charge / discharge 140A',
      '6,000 cycles, 90% DOD',
      'Works with the GETA 3.6kW inverter',
      '5-year warranty',
    ],
    price: 98752.5,
    image: photo('luxpower-li-7-5e'),
  },
  {
    id: 'luxpower-li-15e',
    category: 'solar',
    group: 'batteries',
    name: 'Luxpower Li-15e Stackable Lithium Battery',
    model: 'Li-15e (Low Voltage, IP20)',
    specs: [
      '15kWh, 51.2V, 300Ah',
      'Max charge / discharge 140A',
      '6,000 cycles, 90% DOD',
      'Works with SNA inverters (6kW, 6.6kW and 14kW)',
      '5-year warranty',
    ],
    price: 149325,
    image: photo('luxpower-li-15e'),
  },
  {
    id: 'genixgreen-es-box34-max-plus',
    category: 'solar',
    group: 'batteries',
    name: 'Genixgreen 51.2V 314Ah LiFePO4 Battery',
    model: 'ES-BOX34 MAX Plus',
    specs: [
      '16.08kWh, 51.2V lithium iron phosphate',
      'Max charge / discharge 200A',
      'Over 10,000 cycles (80% DOD)',
      'Floor-standing on wheels, 4.3″ touch screen',
      '5-year warranty',
    ],
    details: [
      'Cell type: Lithium iron phosphate (LFP)',
      'Nominal voltage: 51.2V',
      'Nominal capacity: 314Ah',
      'Nominal energy: 16.08kWh',
      'Standard charge voltage: 56.8V',
      'Discharge cut-off voltage: 44.8V',
      'Max charge / discharge current: 200A',
      'Depth of discharge (DOD): 80%',
      'Cycle life: 10,000 cycles or more (25°C, 0.5C, 80% DOD)',
      'Energy throughput: 35 MWh',
      'Parallel capability: up to 16 units',
      'Display: RGB LED light and 4.3″ LCD touch screen',
      'Communication: RS485, CAN, USB',
      'Charge temperature: 0°C to 55°C',
      'Discharge temperature: −20°C to 55°C',
      'Dimensions (W × D × H): 490 × 840 × 250 mm (excluding wheels)',
      'Weight: 122 kg',
      'Installation: Floor-standing',
      'Certifications: RoHS, UN38.3, MSDS',
      'Warranty: 5 years',
    ],
    price: 110000,
    image: photo('genixgreen-es-box34-max-plus'),
  },

  // ───────────── Monitoring & rapid shutdown ─────────────
  {
    id: 'fonrich-rsd-ttcb',
    category: 'solar',
    group: 'monitoring-safety',
    name: 'Fonrich Rapid Shutdown Device (1 fits 2 PV modules, PLC)',
    model: 'FR-PVMS-TTCB',
    specs: [
      'Max input operating voltage 60V × 2',
      'Max continuous current 20A, 4 mm² cable',
      'Monitors on/off status, module voltage, temperature and energy',
      '10-year warranty',
    ],
    price: 4519.35,
    image: photo('fonrich-rsd-ttcb'),
  },
  {
    id: 'fonrich-plc-transceiver',
    category: 'solar',
    group: 'monitoring-safety',
    name: 'Fonrich Smart PV PLC Transceiver',
    model: 'FR-PVMS-HKB',
    description:
      'Sends data over the power lines (PLC) so you can monitor and manage your solar setup.',
    specs: ['5-year warranty'],
    price: 6334.35,
    image: photo('fonrich-plc-transceiver'),
  },
  {
    id: 'fonrich-monitor-gateway',
    category: 'solar',
    group: 'monitoring-safety',
    name: 'Fonrich Smart PV Monitor & Gateway',
    model: 'FR-PVMS-MGES',
    description:
      'Connects your solar panels to the management platform for performance tracking.',
    specs: ['5-year warranty'],
    price: 12632.4,
    image: photo('fonrich-monitor-gateway'),
  },
  {
    id: 'onccy-ers40-8',
    category: 'solar',
    group: 'monitoring-safety',
    name: 'ONCCY Rapid Shutdown Switch, 8 strings',
    model: 'ERS40-8-MC4',
    description: 'Safety device for solar PV systems.',
    specs: ['Up to 1000V DC', 'Up to 40A', '8 strings', '5-year warranty'],
    price: 24733.5,
  },
  {
    id: 'onccy-ers40-20',
    category: 'solar',
    group: 'monitoring-safety',
    name: 'ONCCY Rapid Shutdown Switch (Firefighter Switch)',
    model: 'ERS40-20-MC4',
    description: 'String-level rapid shutdown device for rooftop PV systems.',
    specs: ['MC4 connectors', 'Up to 10 strings', '1000V DC, 40A per string', '5-year warranty'],
    price: 51133.5,
  },

  // ───────────── Mounting & racking ─────────────
  ...([
    ['2-4', '2.4', 1006.5],
    ['2-8', '2.8', 1171.5],
    ['3-6', '3.6', 1518],
  ] as const).map(
    ([slug, length, price]): Product => ({
      id: `solar-railing-${slug}m`,
      category: 'solar',
      group: 'mounting',
      name: `Solar panel railing, ${length} m`,
      specs: [mountingSpec],
      price,
      image: photo('railing'),
    }),
  ),
  {
    id: 'solar-mid-clamp',
    category: 'solar',
    group: 'mounting',
    name: 'Solar panel mid clamp',
    specs: [mountingSpec, 'Sizes: 30mm & 35mm'],
    price: 62.7,
    image: photo('mid-clamp'),
  },
  {
    id: 'solar-end-clamp',
    category: 'solar',
    group: 'mounting',
    name: 'Solar panel end clamp',
    specs: [mountingSpec, 'Sizes: 30mm, 33mm & 35mm'],
    price: 62.7,
    image: photo('end-clamp'),
  },
  {
    id: 'solar-rail-splice',
    category: 'solar',
    group: 'mounting',
    name: 'Rail splice / connector',
    specs: [mountingSpec],
    price: 95.7,
    image: photo('rail-splice'),
  },
  {
    id: 'solar-ground-lug',
    category: 'solar',
    group: 'mounting',
    name: 'Ground lug',
    specs: [mountingSpec],
    price: 57.75,
    image: photo('ground-lug'),
  },
  {
    id: 'solar-ground-plate-clip',
    category: 'solar',
    group: 'mounting',
    name: 'Ground plate clip',
    specs: [mountingSpec],
    price: 19.8,
    image: photo('ground-plate-clip'),
  },
  {
    id: 'solar-l-foot',
    category: 'solar',
    group: 'mounting',
    name: 'L foot',
    specs: [mountingSpec],
    price: 107.25,
    image: photo('l-foot'),
  },
  {
    id: 'solar-water-drainer',
    category: 'solar',
    group: 'mounting',
    name: 'Water drainer',
    specs: [mountingSpec, 'Sizes: 30mm, 33mm & 35mm'],
    price: 39.6,
    image: photo('water-drainer'),
  },

  // ───────────── Breakers & surge protection (ONCCY) ─────────────
  ...([
    ['ESM1-63/C32/2', 'AC MCB 32A 2P', 'Icn 10kA · Ui 500Vac · Ue 415Vac · 63A frame · C curve', 493.35],
    ['ESM1-63/C50/2', 'AC MCB 50A 2P', 'Icn 10kA · Ui 500Vac · Ue 415Vac · 63A frame · C curve', 542.85],
    ['ESM1-63/C63/2', 'AC MCB 63A 2P', 'Icn 10kA · Ui 500Vac · Ue 415Vac · 63A frame · C curve', 542.85],
    ['EAB1-125H/C100/2', 'AC MCB 100A 2P', 'Icn 10kA · Ui 500Vac · Ue 415Vac · 100A frame · C curve', 955.35],
    ['EAB1-125H/C125/2', 'AC MCB 125A 2P', 'Icn 10kA · Ui 500Vac · Ue 415Vac · 125A frame · C curve', 973.5],
    ['EAM3-63U/63-33', 'AC MCCB 63A 3P', 'Ui AC800 · Ue AC400 · electromagnetic + thermal tripping', 1798.5],
    ['EAM3-125U/125-33', 'AC MCCB 125A 3P', 'Ui AC800 · Ue AC400 · electromagnetic + thermal tripping', 3613.5],
    ['EAM3-400U/400-33', 'AC MCCB 400A 3P', 'Ui AC800 · Ue AC400 · electromagnetic + thermal tripping', 9058.5],
    ['EAM3-630U/500-33', 'AC MCCB 500A 3P', 'Ui AC800 · Ue AC400 · electromagnetic + thermal tripping', 15823.5],
    ['EAP275/40-2', 'AC SPD 20A 2P', 'Type 2 · 275VAC · Imax 40kA · In 20kA', 610.5],
    ['EAP275/40-3', 'AC SPD 20A 3P', 'Type 2 · 275VAC · Imax 40kA · In 20kA', 1303.5],
    ['EDPG40-2', 'DC SPD 20A 2P 600V', 'Type 2 · 600V · Imax 40kA · In 20kA', 973.5],
    ['EDPN40-2', 'DC SPD 20A 2P 1000V', 'Type 2 · 1000V · Imax 40kA · In 20kA', 1138.5],
    ['EDPT20-3', 'DC SPD 20A 3P 1500V', 'Type 2 · 1500V · Imax 20kA · In 10kA', 2128.5],
    ['EDB1-63/C25/2H', 'DC MCB 25A 2P', '6kA · C curve · Ue 600VDC', 742.5],
  ] as const).map(
    ([model, name, spec, price]): Product => ({
      id: `onccy-${model.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`,
      category: 'solar',
      group: 'breakers',
      name: `ONCCY ${name}`,
      model,
      specs: [spec],
      price,
    }),
  ),
];

/** Complete packages, shown on the home page. */
export const solarPackages: Product[] = [
  {
    id: 'essential-hybrid-6kw',
    category: 'solar',
    group: 'packages',
    name: 'Essential Hybrid 6kW',
    description: 'A solid starter system for a typical home.',
    specs: ['SolaX 6.0kW hybrid inverter', '8 × 600W solar panels', '200Ah LiFePO4 battery'],
    price: 282000,
    priceNote: 'All-in with professional installation',
  },
  {
    id: 'hl-power-11kw',
    category: 'solar',
    group: 'packages',
    name: 'HL Power 11kW',
    description: 'More inverter capacity for bigger loads, at a mid-range price.',
    specs: ['11kW HL hybrid inverter', '12 × 600W solar panels', '314Ah Genixgreen LiFePO4 battery'],
    price: 355000,
    priceNote: 'All-in with professional installation',
  },
  {
    id: 'ultimate-heavy-duty-6kw',
    category: 'solar',
    group: 'packages',
    name: 'Ultimate Heavy Duty 6kW',
    description: 'More panels and a bigger battery for longer backup.',
    specs: ['SolaX 6.0kW hybrid inverter', '12 × 600W solar panels', '314Ah LiFePO4 battery'],
    price: 357000,
    priceNote: 'All-in with professional installation',
  },
  {
    id: 'xtriple-tier-1',
    category: 'solar',
    group: 'packages',
    name: 'X Triple Power Tier 1',
    description: '8kW system with an expandable battery.',
    specs: ['SolaX 8kW hybrid inverter', '12 × 600W solar panels', '314Ah LiFePO4 battery (expandable)'],
    price: 405000,
    priceNote: 'All-in with professional installation',
  },
  {
    id: 'xtriple-tier-2',
    category: 'solar',
    group: 'packages',
    name: 'X Triple Power Tier 2',
    description: '10kW system with large-capacity storage.',
    specs: ['SolaX 10kW hybrid inverter', '16 × 600W solar panels', '628Ah LiFePO4 battery'],
    price: 621000,
    priceNote: 'All-in with professional installation',
  },
  {
    id: 'xtriple-tier-3',
    category: 'solar',
    group: 'packages',
    name: 'X Triple Power Tier 3',
    description: 'Maximum power for large homes and businesses.',
    specs: ['SolaX 12kW hybrid inverter', '24 × 600W solar panels', '628Ah LiFePO4 battery'],
    price: 720000,
    priceNote: 'All-in with professional installation',
  },
];

export function findProduct(id: string | undefined) {
  return [...products, ...solarPackages].find((p) => p.id === id);
}

export function formatPrice(price: number) {
  const decimals = Number.isInteger(price) ? 0 : 2;
  return `₱${price.toLocaleString('en-PH', {
    minimumFractionDigits: decimals,
    maximumFractionDigits: decimals,
  })}`;
}
